export * from './MainSection.tsx'
export * from './AboutUsSection.tsx'
export * from './NoticesFacebook.tsx'
export * from './CoursesSection.tsx'
export * from './ContactSection.tsx'
export * from './GallerySection.tsx'
export * from './InstallationsSection.tsx'
export * from './RegistrationsSections.tsx'